#!/bin/sh

# PROVIDE: mc
# REQUIRE: FILESYSTEMS
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="mc"
rcvar="${name}_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

mc_stop()
{
	/usr/local/bin/screen -S mc -p 0 -X stuff "stop^M"
	while pgrep -f server.jar > /dev/null; do sleep 1; done
	/usr/local/bin/screen -S mc -p 0 -X stuff "exit^M"
}

mc_start()
{
        /usr/local/bin/screen -dmS mc
        /usr/local/bin/screen -S mc -p 0 -X stuff "cd /srv/mc/^M"
        /usr/local/bin/screen -S mc -p 0 -X stuff "./start^M"
}

load_rc_config $name
run_rc_command "$1"
